version: '3.4'

services:
  wifianalyzermqtt:
    image: aisstreammqtt
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      mqttHost: 'mqtt://host'
      mqttTopic: 'topic/'
      mqttUserName: ''
      mqttPassword: ''
      aisStreamAPIKey: ''      
      aisStreamMMSI: []    
      aisStreamBoxCornerOneLat: 0
      aisStreamBoxCornerOneLon: 0
      aisStreamBoxCornerTwoLat: 0
      aisStreamBoxCornerTwoLon: 0
